### PR TITLE
refactor(Sensei_Question): quiz feedback upgrade

### PR DESCRIPTION
**Pull request by paulkirspuu**
https://app.clickup.com/t/k1c0p6
styles attached in wp-theme-lib

### CODE REVIEW

**Comment by saas786** [comment]
@paulkirspuu 

Is this still relevant?
Are we using it already?

**Comment by paulkirspuu** [comment]
> @paulkirspuu
> 
> Is this still relevant? Are we using it already?

Relevant, and we're using it already.

**Comment by saas786** [comment]
> > @paulkirspuu
> > Is this still relevant? Are we using it already?
> 
> Relevant, and we're using it already.

@paulkirspuu 
How? as a top patch?

@pawelkmpt last time when you deployed this repo, did you re-apply Paul's code? Or ?

If its being used, I would like to know how? so I can merge this accordingly.

**Comment by pawelkmpt** [comment]
> @pawelkmpt last time when you deployed this repo, did you re-apply Paul's code? Or ?
> 
> If its being used, I would like to know how? so I can merge this accordingly.

Last full deployment was on 2022.09.28 `/home/convers/deploy/plugins/sensei-lms/releases/20220928.105023-pawel/`, what means it was not applied by me. @paulkirspuu must've deployed single file manually.

As I see @paulkirspuu you forgot to request review. It's important to do it but also stop single file deployments unless it's critical. We all need to be at the same page. No more room for silent changes and mess from the past.

EDIT

I just noticed it's October **2021** 😮 

> Relevant, and we're using it already.

Guys, make sure it's really live. With deployments of `master` branch it might not be there.

**Comment by paulkirspuu** [comment]
> As I see @paulkirspuu you forgot to request review. It's important to do it but also stop single file deployments unless it's critical. We all need to be at the same page. No more room for silent changes and mess from the past.

This is from a year ago, back when single file uploads was the way to go. Alongside a PR was opened as per guidelines.

**Comment by paulkirspuu** [comment]
> Guys, make sure it's really live. With deployments of master branch it might not be there.

As mentioned earlier, it's live.

**Comment by paulkirspuu** [comment]
> Last full deployment was on 2022.09.28 /home/convers/deploy/plugins/sensei-lms/releases/20220928.105023-pawel/

Why not pushed to GH?

**Comment by pawelkmpt** [comment]
> > Last full deployment was on 2022.09.28 /home/convers/deploy/plugins/sensei-lms/releases/20220928.105023-pawel/
> 
> Why not pushed to GH?

It's here. I deployed after merging #10

**Comment by paulkirspuu** [comment]
> > > Last full deployment was on 2022.09.28 /home/convers/deploy/plugins/sensei-lms/releases/20220928.105023-pawel/
> > 
> > 
> > Why not pushed to GH?
> 
> It's here. I deployed after merging #10

Would have thought its master, but alright clear.

**Comment by pawelkmpt** [comment]
> Would have thought its master, but alright clear.

Our master is `cxl`

**Comment by paulkirspuu** [comment]
> > Would have thought its master, but alright clear.
> 
> Our master is `cxl`

True, but wasn't always like that. See history https://github.com/conversionxl/sensei/commits/master.

At the time this PR was submitted it was still `master`.

**Comment by pawelkmpt** [comment]
> True, but wasn't always like that. See history https://github.com/conversionxl/sensei/commits/master.
> 
> At the time this PR was submitted it was still `master`.

Indeed. I just changed base for this PR. Please rebase this branch and we'll merge it later.

**Comment by saas786** [comment]
@paulkirspuu If you are okay, I can rebase it and resolve conflicts, as I have worked with it recently.

Also @pawelkmpt is right, we should only keep `master / main / cxl` branches on live, which goes through deployment process, changelog and such.

For testing hotfix, like you do normally, its fine, but if it resolves your issue, should file PR so it gets deployed through a process, so we can track changes and doesn't overwrite untracked patches :)

**Comment by pawelkmpt** [comment]
> @paulkirspuu If you are okay, I can rebase it and resolve conflicts, as I have worked with it recently.

I think it's okay @saas786 You're already working with Sensei so it'll be easier for you to resolve it than for @paulkirspuu to switch context.

**Comment by saas786** [comment]
It turns out, it was already merged to `cxl`.

Ref: https://github.com/conversionxl/sensei/blob/8c8e4b4e37da76ba5c13412e02c4189bf4587cba/includes/class-sensei-question.php#L867

Just made a small refactor, as it uses `str_contains` which is available in php 8.0, we are currently supporting php 7.4.

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
