### PR TITLE
feat: add pending state to action bar buttons

### PR DESCRIPTION
**Pull request by anoblet**
https://app.clickup.com/t/86azbhexr

Depends on: https://github.com/conversionxl/aybolit/pull/397

### CODE REVIEW

**Review by pawelkmpt — COMMENTED** [review]
@anoblet we need it also in `public/wp-content/plugins/sensei-lms/includes/class-sensei-quiz.php`

**Comment by anoblet** [comment]
@pawelkmpt I don't mind adding:

```
this.setAttribute('pending', '');
```

to: https://github.com/conversionxl/sensei/blob/1fbb9dd41f6dd1b93b5230aa9d9c5ad556013fbd/includes/class-sensei-quiz.php#L1361.

I'm not sure which element I could use to review the change.

**Comment by pawelkmpt** [comment]
> I'm not sure which element I could use to review the change.

Quiz submission :)

**Review by pawelkmpt — CHANGES_REQUESTED** [review]
@anoblet please squash commits

**Review by pawelkmpt — APPROVED** [review]

**Pull request merged**
